language: python
matrix:
  include:
  - python: '3.7'
  - python: '3.8'
  - python: '3.9'

cache:
  pip: true

install:
- pip install coverage
- python setup.py install
script:
- coverage run runtests.py
before_deploy:
- git stash --all
- sed -i "s/@@version@@/${TRAVIS_TAG}/g" setup.py
deploy:
  skip_cleanup: true
  provider: pypi
  user: __token__
  password:
    secure: B9kPy8NCzzqKbKurDaclDOcZaTHXVEJiEKBCTrdW37oDe/KU+IyKdHzXWI3Wwzmr+CnsFeNu7eWp/VNJiJf/oMwStRCHWbRwAeMbDO9nDFgKW3elN/OpCZeQOJ9xr+CYjM0jv9u3vGNP7nZxySmwVC66b68xWVmQBl1LK/E2tFAUlEHyLHeduwRyMysXLcUwp1AV+/WdMZL3XHSmPF+jNQ62Rvwm0MgQy8TRIZQPDmY10qpEV/REwpk+eyuJtKPOQy//rlR4A3MOlDa4V7dBNnACn0m07WgcobwNLGEpmOmi5kx7Yd185495I2MPqiCPRYjqWNUX+pOSZS1HSBcRT3GOy0n9LCpDVKKUXaRwXl0wliNxmEN4OgbzKAhd+KVqnBUpHxPh5gBMTOFlR3dxF8Q2nm3Msoox2ufu8IAaxZveEiAh+DBEFGiqleAOkjWIa1TLuDirQlmjoZY3ima9prDcy/yqUt4DnSnkbLUWA3waS+Tlu6u6skB/AzsYFgpVeycCIcd10yzsJ1qmJSgnBUmOM/kh+Eo1W6yk2C2J6IeYF0L2e9AkL7S8zTpLDNEbn+DIw32PX3hRAdjBGdR/TBMc4w4kf39XIZAcChGWWRCBhtQAgY6gH1jj/AxvarxLEyIfnynGhY0q7naw7zOoDeQY+zP+H2i3W3Xq771+3HQ=
  on:
    python: '3.8'
    tags: true
after_script:
- bash <(curl -s https://codecov.io/bash)
